@base_url = http://localhost:8080

##################################################
### AUTH API
##################################################

### 0. Login (Get JWT Token)
# @name login
POST {{base_url}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrEmail": "johndoe",
  "password": "secretPassword123"
}

### Store token in variable for subsequent requests
@authToken = {{login.response.body.token}}


##################################################
### AUTHORS API
##################################################

### 1. Get all authors
GET {{base_url}}/api/authors
Accept: application/json

###

### 2. Create a new author
# @name createAuthor
POST {{base_url}}/api/authors
Content-Type: application/json
Accept: application/json

{
  "firstName": "Robert",
  "lastName": "Martin"
}

###

### 3. Get author by ID
GET {{base_url}}/api/authors/1
Accept: application/json

###

### 4. Update author by ID
PUT {{base_url}}/api/authors/1
Content-Type: application/json
Accept: application/json

{
  "firstName": "Robert C.",
  "lastName": "Martin"
}

###

### 5. Delete author by ID
DELETE {{base_url}}/api/authors/1
Accept: application/json

###


##################################################
### BOOKS API
##################################################

### 6. Get all books
GET {{base_url}}/api/books
Accept: application/json

###

### 7. Create a new book
# @name createBook
POST {{base_url}}/api/books
Content-Type: application/json
Accept: application/json

{
  "isbn": "9780132350884",
  "title": "Clean Code",
  "publishDate": "2008-08-01",
  "authorIds": [
    1
  ]
}

###

### 8. Get book by ID
GET {{base_url}}/api/books/1
Accept: application/json

###

### 9. Update book by ID
PUT {{base_url}}/api/books/1
Content-Type: application/json
Accept: application/json

{
  "isbn": "9780132350884",
  "title": "Clean Code: A Handbook of Agile Software Craftsmanship",
  "publishDate": "2008-08-01",
  "authorIds": [
    1
  ]
}

###

### 10. Delete book by ID
DELETE {{base_url}}/api/books/1
Accept: application/json

###


##################################################
### USERS API
##################################################

### 11. Get all users
GET {{base_url}}/api/users
Accept: application/json

###

### 12. Create a new user
# @name createUser
POST {{base_url}}/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "secretPassword123"
}

###

### 13. Get user by ID
GET {{base_url}}/api/users/1
Accept: application/json

###

### 14. Update user by ID
PUT {{base_url}}/api/users/1
Content-Type: application/json
Accept: application/json

{
  "username": "johndoe_updated",
  "email": "john.updated@example.com",
  "password": "newSecretPassword456"
}

###

### 15. Delete user by ID
DELETE {{base_url}}/api/users/1
Accept: application/json

###
